[tool.autopep8]
max_line_length = 120

[project]
name = "images"
version = "0.1.0"

dependencies = [
    "vmtest @ git+https://github.com/osbuild/bootc-image-builder.git",
]

[tool.setuptools]
packages = []
