---
# This action creates a release every Monday at 5:00 UTC.
name: "Create and push release tag"

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  tag-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Upstream tag
        uses: osbuild/release-action@create-tag
        with:
          token: "${{ secrets.SCHUTZBOT_GITHUB_ACCESS_TOKEN }}"
          username: "imagebuilder-bot"
          email: "imagebuilder-bots+imagebuilder-bot@redhat.com"
          semver: "true"
          semver_bump_type: "minor"
