# This action updates the bootc-image-builder ref in the Schutzfile
---
name: "Update bootc-image-builder ref"

on:
  workflow_dispatch:
  schedule:
    # Every day at 05:00
    - cron: "0 5 * * *"

jobs:
  update-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Apt update
        run: sudo apt update

      - name: Install Dependencies
        run: sudo apt install -y skopeo python3

      - name: Check out main
        uses: actions/checkout@v4
        with:
          path: images
          ref: main

      - name: Update Schutzfile
        working-directory: ./images
        run: |
          ./test/scripts/update-schutzfile-bib
          git diff

      - name: Open PR
        working-directory: ./images
        env:
          GITHUB_TOKEN: ${{ secrets.SCHUTZBOT_GITHUB_ACCESS_TOKEN }}
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git config user.name "schutzbot"
          git config user.email "schutzbot@gmail.com"
          branch="schutzfile-bib-$(date -I)"
          git checkout -b "${branch}"
          git add Schutzfile
          git commit -m "schutzfile: Update bootc-image-builder ref"
          git push -f https://"$GITHUB_TOKEN"@github.com/schutzbot/images.git
          new_ref="$(jq -r '.common."bootc-image-builder".ref' Schutzfile)"
          echo "Updating bootc-image-builder test container ref to ${new_ref}" > body
          gh pr create \
            -t "Update bootc-image-builder ref to latest" \
            -F "body" \
            --repo "osbuild/images" \
            --base "main" \
            --head "schutzbot:${branch}"
